import { Providers } from "@/app/providers";
import "@fontsource/lexend/latin.css";
import { Header } from "@/app/Header";
import { ReactNode } from "react";
import { Box } from "@chakra-ui/layout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <Box m="0 auto" maxWidth={1200} transition="0.5s ease-out" as="body">
        <Providers>
          <Box m={8}>
            <Header />
            <Box as="main" my={22}>
              {children}
            </Box>
          </Box>
        </Providers>
      </Box>
    </html>
  );
}
