import { Providers } from "@/app/providers";
import "@fontsource/lexend/latin.css";
import { Header } from "@/app/Header";
import { ReactNode } from "react";
import { Box } from "@chakra-ui/layout";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <Box m="0 auto" maxWidth={1200} transition="0.5s ease-out" as="body">
        <Providers session={session}>
          <Box m={8}>
            <Header />
            <Box as="main" my={22}>
              {children}
            </Box>
          </Box>
        </Providers>
      </Box>
    </html>
  );
}
